### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by nongdenchet** [nongdenchet/coder_restaurant#1]
I have completed assignment 1
/cc @coderschoolreview

**Comment by nvh0412** [comment]
Hi @nongdenchet,

I love Material Design, :heart: 

Your submission is excellent, you had applied many technique, pattern of rails into this assignment, :tada:  , you had spent your time to create testing spec for your application, amazing. Here's what you might change

## Suggestion
1. **MODEL**
   - [In Food.rb](https://github.com/nongdenchet/coder_restaurant/blob/master/app/models/food.rb#L29)
     increase_views_count, you should use [increment!](http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-increment-21), it will automatically increment the view_count. 
   - [In Review.rb](https://github.com/nongdenchet/coder_restaurant/blob/master/app/models/review.rb#L31): Nice to see `before_create` callback in this model. :100:
     I saw you used StringUtils.rb for checking username and comment  whether null or not, but why don’t you use `blank?` to check this problem?. Or maybe you even can create default value for them by creating migration.
   - Perfect, but you should take a look at some integer fields, it need to have default value. Ah it’s not totally perfect, :joy:, you can use only 1 line for validations if they’re validating the same type. I'm gonna give you an example in your model file then.
2. **CONTROLLER**
   - First thing, you had applied [cookie to cache the order](https://github.com/nongdenchet/coder_restaurant/blob/master/app/helpers/cookies_helper.rb) and you didn’t forget to encode your cookie’s value :100:. But if you decided to use cookie for caching your data, but your data have to encode, you should use session, your data will be encoded by using session. Hehe. :smiling_imp:  You don’t have to encode your data, anymore.
   - [In CookiesHelper](https://github.com/nongdenchet/coder_restaurant/blob/master/app/helpers/cookies_helper.rb#L28): `orders.reduce("") { |result, id| result + "#{id}, “ } <=> orders.join(“,”)`. Is it better?
   - [In MenuController.rb](https://github.com/nongdenchet/coder_restaurant/blob/master/app/controllers/menu_controller.rb#L32)
     `Food.select(:cuisine).map(&:cuisine).uniq <=> Food.pluck(:cuisine).uniq`, you should use pluck in this case, because pluck will return for you an array, but select will return for you ActiveRecordCollection, you don’t want to waste your memory, right?
   - [In OrdersController.rb](https://github.com/nongdenchet/coder_restaurant/blob/master/app/controllers/orders_controller.rb#L31)
     create action, you shouldn’t use create immediately after you initial your object, then you used persistant? to check where saved or not. You have taken 2 times call to database for checking. By using `new` to initial object and using if object.save to check your object be saved or not.
3. **ROUTES**
   - You should try to make your route be REST-ful as possible as you can. It mean you should try to wrap your mapping link into 1 `resource`, you can custom your link then.
4. **VIEWS**
   - [In your food_detail.html.erb](https://github.com/nongdenchet/coder_restaurant/blob/master/app/views/foods/_food_detail.html.erb#L12), you should use `truncate` view helper to restrict the length of food description.
   - [In your show.html.erb](https://github.com/nongdenchet/coder_restaurant/blob/master/app/views/foods/show.html.erb#L15), you can use `<%= render @food %>` to render your partial view :), you don’t have to point out the name of partial view.
   - Finally, You can use `j` instead of `escape_javascript` in [your js.erb[(https://github.com/nongdenchet/coder_restaurant/blob/master/app/views/menu/display.js.erb#L1) file. Look like this:

``` ruby
    $("#display").html("<%= j(render @display_food) %>”);
```

I'm not going to go over your testing spec, because this week, we haven't still learned about testing yet. But i'll give you some advices when i have free time. There’s no denying that you're a one of the best of student in our class, if you have free time, feel free help us to share your knowledge, your experiment on Slack or Facebook group. :dancer: Don't just help Ms LanDoan :smiling_imp: 

Ahhh, don't use `Service` to supply multiple requirement, i mean multiple purpose, Service is served for only one purpose, Ex: if your business to save your food_item too complicated, hence you can create Service for it.

/cc @coderschoolreview /cc @harley.
